name: Container Image Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Container image
      run: docker build . --file docker/Dockerfile --tag localbuild/testimage:latest
    - uses: anchore/scan-action@v2
      with:
        image: "localbuild/testimage:latest"
        acs-report-enable: true
